name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r28b-linux.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r28b
      - name: Build
        run: |
          cd build
          ./make_android_lua53.sh
          sudo apt install gcc-multilib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53
          overwrite: true
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd build
          ./make_linux_lua53.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua54
          overwrite: true
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd build
          ./make_ios_lua53.sh
          ./make_osx_lua53.sh
          ./make_osx_silicon_lua53.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua54
          overwrite: true

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build
          .\make_win_lua53.bat
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua54
          overwrite: true
